FROM rust:1.85.0

WORKDIR /tp_rush

COPY Cargo.toml Cargo.lock ./

RUN cargo fetch

COPY src ./src

RUN cargo build --release

RUN apt update && apt install -y curl

RUN useradd -m test_user

RUN mv /tp_rush/target/release/rush_backend /tp_rush/rush_backend \
    && chmod +x /tp_rush/rush_backend \
    && chown -R test_user:test_user /tp_rush

USER test_user

EXPOSE 8080

CMD ["/tp_rush/rush_backend"]
